query GetPageConfig($id: MongoID!) {
  getPageConfig(_id: $id) {
    _id
    owner_type
    owner_id
    name
    description
    status
    version
    published_version
    template_id
    thumbnail_url
    sections {
      id
      type
      order
      hidden
      props
    }
  }
}

mutation PublishPageConfig($id: MongoID!) {
  publishPageConfig(id: $id) {
    _id
    status
    published_version
  }
}
