query GetSpaceSubscription($space: MongoID!) {
  getSpaceSubscription(space: $space) {
    subscription {
      _id
      space
      status
      current_period_start
      current_period_end
      cancel_at_period_end
    }
    items {
      active
      type
    }
    payment {
      client_secret
      publishable_key
    }
  }
}
