// Maps MCP tool names to GraphQL resolver names.
// MCP tools use snake_case (e.g., search_events),
// but the GraphQL resolvers use camelCase with 'ai' prefix (e.g., aiSearchEvents).

export const TOOL_TO_RESOLVER: Record<string, string> = {
  search_events: 'aiSearchEvents',
  get_event: 'aiGetEvent',
  create_event: 'createEvent',
  update_event: 'updateEvent',
  publish_event: 'aiPublishEvent',
  cancel_event: 'aiCancelEvent',
  get_hosting_events: 'aiGetHostingEvents',
  invite_event: 'aiInviteEvent',
  decide_event_join_requests: 'aiDecideEventJoinRequests',
  get_event_feedback_summary: 'aiGetEventFeedbackSummary',
  list_event_feedbacks: 'aiListEventFeedbacks',
  get_event_checkins: 'aiGetEventCheckins',
  get_event_checkin_insight: 'aiGetEventCheckins',
  list_event_ticket_types: 'aiListEventTicketTypes',
  create_event_ticket_type: 'aiCreateEventTicketType',
  update_event_ticket_type: 'aiUpdateEventTicketType',
  buy_tickets: 'aiBuyTickets',
  calculate_ticket_price: 'aiCalculateTicketPrice',
  get_me: 'aiGetMe',
  list_my_spaces: 'aiListMySpaces',
  create_space: 'createSpace',
  update_space: 'updateSpace',
  get_space_stats: 'aiGetSpaceStats',
  get_space_members: 'aiGetSpaceMembers',
  get_event_guests: 'aiGetEventGuests',
  get_event_guest_stats: 'aiGetEventGuestStats',
  get_event_ticket_sold_insight: 'aiGetEventTicketSoldInsight',
  get_event_view_insight: 'aiGetEventViewInsight',
  get_event_payment_stats: 'aiGetEventPaymentStats',
  get_event_application_answers: 'aiGetEventApplicationAnswers',
  get_notifications: 'aiGetNotifications',
  read_notifications: 'aiReadNotifications',
  generate_page_from_description: 'aiGeneratePageFromDescription',
  create_page_config: 'aiCreatePageConfig',
  update_page_config_section: 'aiUpdatePageConfigSection',
  suggest_sections: 'aiSuggestSections',
  page_config_get: 'getPageConfig',
  page_config_update: 'updatePageConfig',
  page_config_published: 'getPublishedConfig',
  page_preview_link: 'generatePreviewLink',
  page_config_create: 'createPageConfig',
  get_backend_version: 'aiGetBackendVersion',
  list_chains: 'aiListChains',
  accept_event: 'aiAcceptEvent',
  decline_event: 'aiDeclineEvent',
  list_payment_accounts: 'listNewPaymentAccounts',
  payment_account_create_wallet: 'createNewPaymentAccount',
  payment_account_create_safe: 'createNewPaymentAccount',
  payment_account_create_escrow: 'createNewPaymentAccount',
  payment_account_create_relay: 'createNewPaymentAccount',
  payment_account_create_stake: 'createNewPaymentAccount',
  payment_account_create_stripe: 'createNewPaymentAccount',
  payment_account_update: 'updateNewPaymentAccount',
  stripe_disconnect: 'disconnectStripeAccount',
  stripe_capabilities: 'getStripeConnectedAccountCapability',
  safe_free_limit: 'getSafeFreeLimit',
  tickets_create: 'createTickets',
  tickets_cancel: 'cancelTickets',
  tickets_assign: 'assignTickets',
  tickets_upgrade: 'upgradeTicket',
  tickets_email: 'mailEventTicket',
  tickets_email_receipt: 'mailTicketPaymentReceipt',
  event_payments_list: 'listEventPayments',
  event_payment_detail: 'getEventPayment',
  event_payment_summary: 'getEventPaymentSummary',
  event_payment_statistics: 'getEventPaymentStatistics',
  newsletter_list: 'listSpaceNewsletters',
  newsletter_get: 'getSpaceNewsletter',
  newsletter_create: 'createSpaceNewsletter',
  newsletter_update: 'updateSpaceNewsletter',
  newsletter_delete: 'deleteSpaceNewsletter',
  newsletter_test_send: 'sendSpaceNewsletterTestEmails',
  newsletter_stats: 'getSpaceNewsletterStatistics',
  space_event_requests: 'getSpaceEventRequests',
  space_event_requests_decide: 'decideSpaceEventRequests',
  space_event_summary: 'getSpaceEventSummary',
  space_sending_quota: 'getSpaceSendingQuota',
  space_my_event_requests: 'getMySpaceEventRequests',
  space_role_features: 'listSpaceRoleFeatures',
  space_role_features_update: 'updateSpaceRoleFeatures',
  space_member_growth: 'getSpaceMemberAmountByDate',
  space_top_attendees: 'getTopSpaceEventAttendees',
  space_location_leaderboard: 'getSpaceEventLocationsLeaderboard',
  cubejs_token: 'generateCubejsToken',
  space_reward_stats: 'getSpaceRewardStatistics',
  event_latest_views: 'getEventLatestViews',
  file_upload: 'createFileUploads',
  file_upload_url: 'createFile',
  space_set_avatar: 'updateSpace',
  space_set_cover: 'updateSpace',
  event_set_photos: 'updateEvent',
};

// Maps MCP tool names to CLI command group + subcommand
export const TOOL_TO_COMMAND: Record<string, { group: string; subcommand: string }> = {
  search_events: { group: 'event', subcommand: 'search' },
  get_event: { group: 'event', subcommand: 'get' },
  create_event: { group: 'event', subcommand: 'create' },
  update_event: { group: 'event', subcommand: 'update' },
  publish_event: { group: 'event', subcommand: 'publish' },
  cancel_event: { group: 'event', subcommand: 'cancel' },
  get_hosting_events: { group: 'event', subcommand: 'list' },
  invite_event: { group: 'event', subcommand: 'invite' },
  decide_event_join_requests: { group: 'event', subcommand: 'approvals' },
  get_event_feedback_summary: { group: 'event', subcommand: 'feedback-summary' },
  list_event_feedbacks: { group: 'event', subcommand: 'feedbacks' },
  get_event_checkins: { group: 'event', subcommand: 'checkins' },
  get_event_checkin_insight: { group: 'event', subcommand: 'checkin-insight' },
  list_event_ticket_types: { group: 'tickets', subcommand: 'types' },
  create_event_ticket_type: { group: 'tickets', subcommand: 'create-type' },
  update_event_ticket_type: { group: 'tickets', subcommand: 'update-type' },
  buy_tickets: { group: 'tickets', subcommand: 'buy' },
  calculate_ticket_price: { group: 'tickets', subcommand: 'price' },
  get_me: { group: 'auth', subcommand: 'whoami' },
  list_my_spaces: { group: 'space', subcommand: 'list' },
  create_space: { group: 'space', subcommand: 'create' },
  update_space: { group: 'space', subcommand: 'update' },
  get_space_stats: { group: 'space', subcommand: 'analytics' },
  get_space_members: { group: 'space', subcommand: 'members' },
  get_event_guests: { group: 'event', subcommand: 'guests' },
  get_event_guest_stats: { group: 'event', subcommand: 'guest-stats' },
  get_event_ticket_sold_insight: { group: 'event', subcommand: 'ticket-insights' },
  get_event_view_insight: { group: 'event', subcommand: 'view-insights' },
  get_event_payment_stats: { group: 'event', subcommand: 'payment-stats' },
  get_event_application_answers: { group: 'event', subcommand: 'applications' },
  get_notifications: { group: 'notifications', subcommand: 'list' },
  read_notifications: { group: 'notifications', subcommand: 'read' },
  generate_page_from_description: { group: 'site', subcommand: 'generate' },
  create_page_config: { group: 'site', subcommand: 'create-page' },
  update_page_config_section: { group: 'site', subcommand: 'update-section' },
  suggest_sections: { group: 'site', subcommand: 'suggest-sections' },
  get_backend_version: { group: 'system', subcommand: 'version' },
  list_chains: { group: 'system', subcommand: 'chains' },
  accept_event: { group: 'event', subcommand: 'accept' },
  decline_event: { group: 'event', subcommand: 'decline' },
};
