// Maps canonical tool names to GraphQL resolver names.
// Tool names use snake_case (e.g., event_search),
// and the GraphQL resolvers use camelCase with 'ai' prefix (e.g., aiSearchEvents).

export const TOOL_TO_RESOLVER: Record<string, string> = {
  event_search: 'aiSearchEvents',
  event_get: 'getEvent',
  event_create: 'createEvent',
  event_update: 'updateEvent',
  event_publish: 'aiPublishEvent',
  event_cancel: 'cancelEvent',
  event_list: 'getHostingEvents',
  event_invite: 'inviteEvent',
  event_approvals: 'decideUserJoinRequests',
  event_feedback_summary: 'aiGetEventFeedbackSummary',
  event_feedbacks: 'listEventFeedBacks',
  event_checkins: 'getEventCheckins',
  tickets_list_types: 'listEventTicketTypes',
  tickets_create_type: 'createEventTicketType',
  tickets_update_type: 'updateEventTicketType',
  tickets_buy: 'aiBuyTickets',
  tickets_price: 'calculateTicketsPricing',
  get_me: 'getMe',
  space_list: 'listMySpaces',
  space_create: 'createSpace',
  space_update: 'updateSpace',
  space_stats: 'getSpaceStatistics',
  space_members: 'listSpaceMembers',
  space_add_member: 'addSpaceMembers',
  space_remove_member: 'deleteSpaceMembers',
  space_connectors: 'spaceConnections',
  event_guests: 'listEventGuests',
  event_guest_stats: 'getEventGuestsStatistics',
  event_ticket_sold_insight: 'getEventTicketSoldChartData',
  event_view_insight: 'getEventViewChartData',
  event_payment_stats: 'getEventPaymentStatistics',
  event_application_answers: 'aiGetEventApplicationAnswers',
  notifications_list: 'getNotifications',
  notifications_read: 'readNotifications',
  notification_filters_list: 'getNotificationFilters',
  notification_filters_set: 'setNotificationFilter',
  notification_filters_delete: 'deleteNotificationFilter',
  notification_channel_preferences_list: 'getNotificationChannelPreferences',
  notification_channel_preferences_set: 'setNotificationChannelPreference',
  notification_channel_preferences_delete: 'deleteNotificationChannelPreference',
  page_section_catalog: 'getSectionCatalog',
  page_config_get: 'getPageConfig',
  page_config_update: 'updatePageConfig',
  page_config_published: 'getPublishedConfig',
  page_preview_link: 'createPreviewLink',
  page_config_create: 'createPageConfig',
  get_backend_version: 'aiGetBackendVersion',
  list_chains: 'listChains',
  accept_event: 'acceptEvent',
  decline_event: 'declineEvent',
  list_payment_accounts: 'listNewPaymentAccounts',
  payment_account_create_wallet: 'createNewPaymentAccount',
  payment_account_create_safe: 'createNewPaymentAccount',
  payment_account_create_escrow: 'createNewPaymentAccount',
  payment_account_create_relay: 'createNewPaymentAccount',
  payment_account_create_stake: 'createNewPaymentAccount',
  payment_account_create_stripe: 'createNewPaymentAccount',
  payment_account_update: 'updateNewPaymentAccount',
  stripe_disconnect: 'disconnectStripeAccount',
  stripe_capabilities: 'getStripeConnectedAccountCapability',
  safe_free_limit: 'getSafeFreeLimit',
  tickets_create: 'createTickets',
  tickets_cancel: 'cancelTickets',
  tickets_assign: 'assignTickets',
  tickets_upgrade: 'upgradeTicket',
  tickets_email: 'mailEventTicket',
  tickets_email_receipt: 'mailTicketPaymentReceipt',
  event_payments_list: 'listEventPayments',
  event_payment_detail: 'getEventPayment',
  event_payment_summary: 'getEventPaymentSummary',
  event_payment_statistics: 'getEventPaymentStatistics',
  newsletter_list: 'listSpaceNewsletters',
  newsletter_get: 'getSpaceNewsletter',
  newsletter_create: 'createSpaceNewsletter',
  newsletter_update: 'updateSpaceNewsletter',
  newsletter_delete: 'deleteSpaceNewsletter',
  newsletter_test_send: 'sendSpaceNewsletterTestEmails',
  newsletter_stats: 'getSpaceNewsletterStatistics',
  space_event_requests: 'getSpaceEventRequests',
  space_event_requests_decide: 'decideSpaceEventRequests',
  space_event_summary: 'getSpaceEventSummary',
  space_sending_quota: 'getSpaceSendingQuota',
  space_my_event_requests: 'getMySpaceEventRequests',
  space_role_features: 'listSpaceRoleFeatures',
  space_role_features_update: 'updateSpaceRoleFeatures',
  space_member_growth: 'getSpaceMemberAmountByDate',
  space_top_attendees: 'getTopSpaceEventAttendees',
  space_location_leaderboard: 'getSpaceEventLocationsLeaderboard',
  cubejs_token: 'generateCubejsToken',
  space_reward_stats: 'getSpaceRewardStatistics',
  event_latest_views: 'getEventLatestViews',
  file_upload: 'createFileUploads',
  file_upload_url: 'createFile',
  space_set_avatar: 'updateSpace',
  space_set_cover: 'updateSpace',
  event_set_photos: 'updateEvent',
  event_session_reservations: 'getEventSessionReservations',
  event_session_reservation_summary: 'getEventSessionReservationSummary',
  event_session_reserve: 'createEventSessionReservation',
  event_session_unreserve: 'deleteEventSessionReservation',
  event_votings: 'listEventVotings',
  event_vote: 'castVote',
};

// Maps canonical tool names to CLI command group + subcommand
export const TOOL_TO_COMMAND: Record<string, { group: string; subcommand: string }> = {
  event_search: { group: 'event', subcommand: 'search' },
  event_get: { group: 'event', subcommand: 'get' },
  event_create: { group: 'event', subcommand: 'create' },
  event_update: { group: 'event', subcommand: 'update' },
  event_publish: { group: 'event', subcommand: 'publish' },
  event_cancel: { group: 'event', subcommand: 'cancel' },
  event_list: { group: 'event', subcommand: 'list' },
  event_invite: { group: 'event', subcommand: 'invite' },
  event_approvals: { group: 'event', subcommand: 'approvals' },
  event_feedback_summary: { group: 'event', subcommand: 'feedback-summary' },
  event_feedbacks: { group: 'event', subcommand: 'feedbacks' },
  event_checkins: { group: 'event', subcommand: 'checkins' },
  tickets_list_types: { group: 'tickets', subcommand: 'types' },
  tickets_create_type: { group: 'tickets', subcommand: 'create-type' },
  tickets_update_type: { group: 'tickets', subcommand: 'update-type' },
  tickets_buy: { group: 'tickets', subcommand: 'buy' },
  tickets_price: { group: 'tickets', subcommand: 'price' },
  get_me: { group: 'auth', subcommand: 'whoami' },
  space_list: { group: 'space', subcommand: 'list' },
  space_create: { group: 'space', subcommand: 'create' },
  space_update: { group: 'space', subcommand: 'update' },
  space_stats: { group: 'space', subcommand: 'analytics' },
  space_members: { group: 'space', subcommand: 'members' },
  event_guests: { group: 'event', subcommand: 'guests' },
  event_guest_stats: { group: 'event', subcommand: 'guest-stats' },
  event_ticket_sold_insight: { group: 'event', subcommand: 'ticket-insights' },
  event_view_insight: { group: 'event', subcommand: 'view-insights' },
  event_payment_stats: { group: 'event', subcommand: 'payment-stats' },
  event_application_answers: { group: 'event', subcommand: 'applications' },
  notifications_list: { group: 'notifications', subcommand: 'list' },
  notifications_read: { group: 'notifications', subcommand: 'read' },
  page_section_catalog: { group: 'site', subcommand: 'section-catalog' },
  get_backend_version: { group: 'system', subcommand: 'version' },
  list_chains: { group: 'system', subcommand: 'chains' },
  accept_event: { group: 'event', subcommand: 'accept' },
  decline_event: { group: 'event', subcommand: 'decline' },
};
